bot:
  token: ${BOT_TOKEN}
  admin-names: under
  session-time-seconds: ${SESSION_TIME:1200}
  
  
# cron parts
cron.session.start: 0 0 21 * * TUE
cron.session.stop: 0 0 0 * * WED

spring:
  datasource:
    url: jdbc:h2:~/bot-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true